import { health, bootstrapData, getCatalog, submitAction, queueStatus } from './api.v53.9.js';
import { MODE_META, ENABLE_IDLE_PRELOAD } from './config.v53.9.js';
import { state, setMode, setCatalog, clearDraft } from './state.v53.9.js';
import { renderHeader, renderModeButtons, renderList, showMessage, collectRows, $ } from './ui.v53.9.js';
import { uid } from './utils.v53.9.js';
async function init(){ renderHeader(); renderModeButtons(changeMode); $('saveBtn').addEventListener('click', save); $('employee').value=localStorage.getItem('realstock.employee')||''; $('employee').addEventListener('input',()=>localStorage.setItem('realstock.employee',$('employee').value)); try{ const h=await health(); showMessage(h.ok?'เชื่อมต่อสำเร็จ':'เชื่อมต่อไม่สำเร็จ',h.ok?'success':'error'); await bootstrapData().catch(()=>null); await changeMode('count'); if(ENABLE_IDLE_PRELOAD) setTimeout(()=>['receive','issue','order'].forEach(m=>getCatalog(m).then(j=>j.ok&&setCatalog(m,j.rows))),500); }catch(e){ showMessage('โหลดไม่สำเร็จ: '+(e.message||e),'error'); } }
async function changeMode(mode){ setMode(mode); showMessage('กำลังโหลด '+MODE_META[mode].label+'...','info'); const json=await getCatalog(mode); if(!json.ok) return showMessage(json.message||'โหลด catalog ไม่สำเร็จ','error'); setCatalog(mode,json.rows||[]); clearDraft(); renderList(()=>renderList(()=>{})); showMessage('พร้อมใช้งาน','success'); }
async function save(){ const rows=collectRows($('employee').value); if(!rows.length) return showMessage('ยังไม่ได้กรอกจำนวน','error'); const requestId=uid('req'); showMessage('กำลังบันทึกเข้าคิว...','info'); const res=await submitAction(state.mode, requestId, rows); if(res.ok){ clearDraft(); renderList(()=>renderList(()=>{})); showMessage(`บันทึกเข้าคิวแล้ว (${rows.length} รายการ)`, 'success'); setTimeout(async()=>{ const q=await queueStatus().catch(()=>null); if(q&&q.ok) showMessage(`Queue: Pending ${q.pending} / Error ${q.error}`,'info'); }, 800); } else { showMessage(res.message||'บันทึกไม่สำเร็จ','error'); } }
window.RealStockApp={init,changeMode,save};
init();
