import { MODE_META, MAX_RENDER_ITEMS_STEP } from './config.v53.9.js';
import { state, setQty } from './state.v53.9.js';
import { esc } from './utils.v53.9.js';
export function $(id){ return document.getElementById(id); }
export function showMessage(msg, type='info'){ const el=$('message'); if(!el)return; el.className=`message ${type}`; el.textContent=msg; }
export function renderHeader(){ $('versionLabel') && ($('versionLabel').textContent='v54.1.3 queue'); }
export function renderModeButtons(onClick){ const box=$('modeButtons'); if(!box)return; box.innerHTML=['count','receive','issue','order'].map(m=>`<button class="mode ${MODE_META[m].color}" data-mode="${m}">${MODE_META[m].label}</button>`).join(''); box.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>onClick(b.dataset.mode))); }
export function renderList(onLoadMore){ const mode=state.mode; const meta=MODE_META[mode]; document.body.dataset.mode=mode; $('modeTitle').textContent=meta.label; $('modeHelper').textContent=meta.helper; $('saveBtn').textContent=meta.saveLabel || 'บันทึก'; $('saveBtn').style.display=mode==='order'?'none':'block'; const rows=(state.catalog[mode]||[]); const visible=rows.slice(0,state.visibleCount); const list=$('itemList'); list.innerHTML=visible.map(renderItem).join('') || '<div class="empty">ไม่มีรายการ</div>'; list.querySelectorAll('.qty').forEach(inp=>inp.addEventListener('input',()=>setQty(inp.dataset.key, inp.value))); const more=$('loadMoreBtn'); if(more){ more.style.display=rows.length>state.visibleCount?'block':'none'; more.onclick=()=>{ state.visibleCount += MAX_RENDER_ITEMS_STEP; onLoadMore(); }; } }
function renderItem(r){ const key=esc(r.item_key); const name=esc(r.item_name_th || r.item_name || key); const zone=esc(r.mode_target_label || r.count_zone_th || 'ไม่ระบุโซน'); const unit=esc(r.display_stock_unit || r.base_unit || r.unit || ''); return `<div class="item"><div><b>${name}</b><div class="meta">${zone}${unit?' · '+unit:''}</div></div><input class="qty" data-key="${key}" inputmode="decimal" placeholder="0" /></div>`; }
export function collectRows(employee){ const mode=state.mode; const byKey={}; (state.catalog[mode]||[]).forEach(r=>byKey[r.item_key]=r); return Object.entries(state.draft).filter(([,v])=>String(v).trim()!=='' && Number(v)!==0).map(([key,qty])=>{ const r=byKey[key]||{}; return { item_key:key, item_name:r.item_name||r.item_name_th||'', brand:r.brand||'', qty:Number(qty), qty_input:qty, unit:r.display_stock_unit||r.base_unit||r.unit||'', base_unit:r.base_unit||r.unit||'', purchase_unit:r.purchase_unit||'', conversion_qty:r.conversion_qty||1, stock_zone:r.mode_target_key||r.count_zone||'', location:r.mode_target_key||r.count_zone||'', mode_target:r.mode_target_key||'', employee:employee||'' }; }); }
